# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthcharacter', '0002_auto_20170616_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilitylist',
            name='associated_occupations',
        ),
        migrations.RemoveField(
            model_name='associatedoccuabil',
            name='ability',
        ),
        migrations.RemoveField(
            model_name='associatedoccuabil',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='associatedoccudrive',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='occupationlist',
            name='occupational_abilities',
        ),
        migrations.AddField(
            model_name='associatedoccuabil',
            name='associated_occupations',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='birthcharacter.OccupationList'),
        ),
        migrations.AddField(
            model_name='associatedoccuabil',
            name='occupational_abilities',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='birthcharacter.AbilityList'),
        ),
        migrations.AddField(
            model_name='associatedoccudrive',
            name='associated_occupations',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='birthcharacter.OccupationList'),
        ),
        migrations.AlterField(
            model_name='abilityexamples',
            name='ability',
            field=models.ForeignKey(default='unassigned_example', on_delete=django.db.models.deletion.SET_DEFAULT, to='birthcharacter.AbilityList'),
        ),
        migrations.AlterField(
            model_name='associatedoccudrive',
            name='drive',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='birthcharacter.DriveList'),
        ),
        migrations.AlterField(
            model_name='driveexamples',
            name='drive',
            field=models.ForeignKey(default='unassigned_example', on_delete=django.db.models.deletion.SET_DEFAULT, to='birthcharacter.DriveList'),
        ),
    ]
