# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthcharacter', '0003_auto_20170616_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionstatus',
            name='comments',
            field=models.TextField(blank=True, verbose_name='comments which have been associated with this record'),
        ),
    ]
