# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthcharacter', '0004_auto_20170616_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialList',
            fields=[
                ('revisionstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='birthcharacter.RevisionStatus')),
                ('special', models.TextField(verbose_name='the special benefits rendered onto a character of this occupation')),
            ],
            bases=('birthcharacter.revisionstatus',),
        ),
        migrations.RemoveField(
            model_name='occupationlist',
            name='special',
        ),
        migrations.AddField(
            model_name='associatedoccuabil',
            name='ability_options',
            field=models.IntegerField(default=False, verbose_name='this association is for a choice from several options'),
        ),
        migrations.AddField(
            model_name='associatedoccuabil',
            name='conditional_options',
            field=models.CharField(blank=True, max_length=75, verbose_name='any restrictions or modifiers'),
        ),
        migrations.AlterField(
            model_name='revisionstatus',
            name='original',
            field=models.BooleanField(verbose_name='TRUE: this record from the Trail of Cthulhu FALSE: it been reworked for the new modern day setting'),
        ),
        migrations.AlterField(
            model_name='revisionstatus',
            name='pulp',
            field=models.BooleanField(verbose_name='relevant for pulp settings'),
        ),
        migrations.AlterField(
            model_name='revisionstatus',
            name='purist',
            field=models.BooleanField(verbose_name='relevant for purist settings'),
        ),
        migrations.AddField(
            model_name='speciallist',
            name='occupation',
            field=models.ForeignKey(default='unassigned_special', on_delete=django.db.models.deletion.SET_DEFAULT, to='birthcharacter.OccupationList'),
        ),
    ]
