# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthcharacter', '0007_auto_20170617_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitylist',
            name='investigative_type',
            field=models.CharField(blank=True, choices=[('A', 'Academic ability'), ('I', 'Interpersonal abilty'), ('T', 'Technical ability')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
