# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthcharacter', '0008_auto_20170617_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitylist',
            name='investigative_type',
            field=models.CharField(blank=True, choices=[('A', 'Academic ability'), ('I', 'Interpersonal abilty'), ('T', 'Technical ability'), ('D', 'Doubles as an investigative ability')], max_length=1),
        ),
    ]
