# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthcharacter', '0009_auto_20170617_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedoccuabil',
            name='options_pool',
            field=models.IntegerField(default=False, verbose_name='this association is for a choice from several options, from Y'),
        ),
        migrations.AlterField(
            model_name='associatedoccuabil',
            name='ability_options',
            field=models.IntegerField(default=False, verbose_name='this association is for a choice from several options, choose X'),
        ),
    ]
