# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthcharacter', '0011_auto_20170618_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatedoccuabil',
            name='ability_options',
            field=models.IntegerField(blank=True, null=True, verbose_name='this association is for a choice from several options, choose X'),
        ),
        migrations.AlterField(
            model_name='associatedoccuabil',
            name='options_pool',
            field=models.IntegerField(blank=True, null=True, verbose_name='this association is for a choice from several options, from Y'),
        ),
    ]
